<?php

namespace App\Http\Controllers;

use App\Models\Asistencia;
use App\Models\Estudiante;
use App\Models\Seccion;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Laravel\Swagger\Attributes\SwaggerResponse;
use Laravel\Swagger\Attributes\SwaggerSection;
use Laravel\Swagger\Attributes\SwaggerSummary;
use App\Utils\ApiResponse;
use App\Http\Mock\AsistenciaMock;
use App\Enums\RoleEnum;
use App\Http\Requests\RegistrarAsistenciaRequest;
use App\Services\ReglaAsistenciaService;
use App\Http\Resources\AsistenciaResource;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

#[SwaggerSection('Asistencias')]
class AsistenciaController extends Controller
{
    // ──────────────────────────────────────────────────────────────────────────
    // QR generation — one QR per section, generated by a teacher/admin
    // ──────────────────────────────────────────────────────────────────────────

    #[SwaggerSummary('Genera el QR para una sección (logo + degradado) devuelto en formato base64. El payload va cifrado.')]
    #[SwaggerResponse(AsistenciaMock::GENERAR_QR_SUCCESS)]
    public function generarQr(Request $request, mixed $seccion): JsonResponse
    {

        $seccion = Seccion::with('horario')
            ->where('id', $seccion)
            ->where('estado', true)
            ->first();

        if (! $seccion) {
            throw new BadRequestHttpException('La sección no existe o no está activa.');
        }

        if (! $seccion->horario_id || ! $seccion->horario?->estado) {
            throw new BadRequestHttpException('La sección no tiene un horario activo asignado.');
        }

        $payload = Crypt::encrypt([
            'seccion_id' => $seccion->id,
            'horario_id' => $seccion->horario_id,
            'fecha'      => now()->toDateString(),
        ]);


        $qr = \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')
            ->size(300)
            ->errorCorrection('H')
            ->style('round') // Puntos redondeados
            ->eye('circle')  // Ojos circulares
            ->gradient(239, 127, 2, 52, 28, 0, 'diagonal'); // Naranja a Marrón Oscuro (colores del logo)

        $logoPath = public_path('logo_qr.png');
        if (file_exists($logoPath)) {
            $qr = $qr->merge($logoPath, 0.2, true);
        }

        $png = (string) $qr->generate($payload);
        $base64 = 'data:image/png;base64,' . base64_encode($png);

        return ApiResponse::success([
            'success'   => true,
            'qr_base64' => $base64,
            'seccion'   => [
                'id'      => $seccion->id,
                'nombre'  => $seccion->nombre,
                'horario' => $seccion->horario->nombre,
            ]
        ], 'QR generado exitosamente');
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Attendance registration — student scans the section QR while authenticated
    // ──────────────────────────────────────────────────────────────────────────

    #[SwaggerSummary('El estudiante autenticado registra su asistencia escaneando el QR de su sección.')]
    #[SwaggerResponse(AsistenciaMock::REGISTRAR_ASISTENCIA_SUCCESS)]
    public function registrar(RegistrarAsistenciaRequest $request, ReglaAsistenciaService $reglaAsistenciaService): JsonResponse
    {
        $user = $request->user();

        if ($user->role()->where('nombre', RoleEnum::ALUMNO)->doesntExist()) {
            return ApiResponse::error('Solo los estudiantes pueden registrar asistencia.', 403);
        }


        $estudiante = Estudiante::with(['seccion.horario'])
            ->where('user_id', $user->id)
            ->where('estado', true)
            ->first();

        if (!$estudiante) {
            return ApiResponse::error('No se encontró un estudiante activo asociado al usuario autenticado.', 403);
        }

        // ── 2. Decrypt and validate the QR payload ────────────────────────────
        $raw = $request->input('qr_token');

        if (!$raw)
            return ApiResponse::error('El código QR es requerido.', 422);


        try {
            $data = $this->descryptQrPayload($raw);

            if ($estudiante->seccion_id !==  $data['seccion_id']) {
                return ApiResponse::error('El estudiante no pertenece a la sección del QR.', 403);
            }

            DB::beginTransaction();
            // ── 5. Resolve the schedule ───────────────────────────────────────────
            $horario = $estudiante->seccion->horario;

            // ── 6. Time calculations ──────────────────────────────────────────────
            $ahora = Carbon::now();
            $fecha = $ahora->toDateString();
            $hora  = $ahora->format('H:i:s');

            $inicio  = $ahora->copy()->setTimeFromTimeString($horario->hora_entrada);
            $limite  = $inicio->copy()->addMinutes((int) $horario->tolerancia);

            // Determinar el estado de asistencia según el horario y la tolerancia.
            // La lógica de PRESENTE, TARDIA y AUSENTE se gestiona en ReglaAsistenciaService.
            
            $estado = $reglaAsistenciaService->determinarEstado(
                $ahora,
                 $horario->hora_entrada,
                (int) $horario->tolerancia
            );

            $esAusente = $estado === 'AUSENTE';

            $limiteTxt = $limite->format('H:i');

            $observaciones = match ($estado) {
                'AUSENTE' => "Llegó a las {$hora}. Fuera del límite permitido ({$limiteTxt}).",
                'TARDIA'  => "Llegó a las {$hora}. Tardío (límite: {$limiteTxt}).",
                default   => "Llegó a las {$hora}. A tiempo.",
            };

            $yaRegistrada = Asistencia::where('estudiante_id', $estudiante->id)
                ->where('fecha_asistencia', $fecha)
                ->exists();

            if ($yaRegistrada) {
                DB::rollBack();

                return ApiResponse::error('La asistencia ya fue registrada para hoy.', 409);
            }

            $asistencia = Asistencia::create([
                'estudiante_id'    => $estudiante->id,
                'fecha_asistencia' => $fecha,
                'hora_entrada'     => $hora,
                'estado'           => $estado,
                'observaciones'    => $observaciones,
                'registrado_por'   => $user->id,
            ]);

            DB::commit();
            if ($esAusente) {
                return ApiResponse::error('Fuera del horario permitido. Registrado como AUSENTE.', 403);
            }

            return ApiResponse::success(new AsistenciaResource($asistencia), 'Asistencia registrada correctamente.');
        } catch (BadRequestHttpException $e) {
            DB::rollBack();
            return ApiResponse::error($e->getMessage(), 400);
        } catch (\Throwable $e) {

            DB::rollBack();
            return ApiResponse::error('Error inesperado: ' . $e->getMessage(), 500);
        }
    }


    // ──────────────────────────────────────────────────────────────────────────
    // Attendance history — the authenticated student views their own records
    // ──────────────────────────────────────────────────────────────────────────

    #[SwaggerSummary('Historial paginado de las asistencias del estudiante autenticado, más recientes primero. Admite "per_page" (máx. 100) además de "page".')]
    #[SwaggerResponse(AsistenciaMock::HISTORIAL_SUCCESS)]
    public function historial(Request $request): JsonResponse
    {
        $user = $request->user();

        $estudiante = Estudiante::where('user_id', $user->id)
            ->where('estado', true)
            ->first();

        if (! $estudiante) {
            return ApiResponse::error('No se encontró un estudiante activo asociado al usuario autenticado.', 404);
        }

        $perPage = min(max($request->integer('per_page', 15), 1), 100);

        $asistencias = Asistencia::where('estudiante_id', $estudiante->id)
            ->orderByDesc('fecha_asistencia')
            ->orderByDesc('hora_entrada')
            ->paginate($perPage);

        return AsistenciaResource::collection($asistencias)->response();
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Attendance report — Docente/Admin view attendance across students
    // ──────────────────────────────────────────────────────────────────────────

    #[SwaggerSummary('Reporte paginado de asistencias de todos los estudiantes, para Docente/Admin. Filtra por "seccion_id", "grado_id", "estado" (PRESENTE/TARDIA/AUSENTE) y rango de fechas ("fecha_desde"/"fecha_hasta"). Admite "per_page" (máx. 100) además de "page".')]
    #[SwaggerResponse(AsistenciaMock::REPORTE_SUCCESS)]
    public function reporte(Request $request): JsonResponse
    {
        $request->validate([
            'seccion_id'  => ['sometimes', 'integer', 'exists:secciones,id'],
            'grado_id'    => ['sometimes', 'integer', 'exists:grados,id'],
            'fecha_desde' => ['sometimes', 'date'],
            'fecha_hasta' => ['sometimes', 'date', 'after_or_equal:fecha_desde'],
            'estado'      => ['sometimes', Rule::in(['PRESENTE', 'TARDIA', 'AUSENTE'])],
            'per_page'    => ['sometimes', 'integer', 'min:1', 'max:100'],
        ]);

        $perPage = min(max($request->integer('per_page', 15), 1), 100);

        $asistencias = Asistencia::with('estudiante.seccion.grado')
            ->when($request->filled('seccion_id'), fn ($query) => $query->whereHas(
                'estudiante',
                fn ($estudianteQuery) => $estudianteQuery->where('seccion_id', $request->integer('seccion_id')),
            ))
            ->when($request->filled('grado_id'), fn ($query) => $query->whereHas(
                'estudiante.seccion',
                fn ($seccionQuery) => $seccionQuery->where('grado_id', $request->integer('grado_id')),
            ))
            ->when($request->filled('fecha_desde'), fn ($query) => $query->where('fecha_asistencia', '>=', $request->query('fecha_desde')))
            ->when($request->filled('fecha_hasta'), fn ($query) => $query->where('fecha_asistencia', '<=', $request->query('fecha_hasta')))
            ->when($request->filled('estado'), fn ($query) => $query->where('estado', $request->query('estado')))
            ->orderByDesc('fecha_asistencia')
            ->orderByDesc('hora_entrada')
            ->paginate($perPage);

        return AsistenciaResource::collection($asistencias)->response();
    }

    private function descryptQrPayload(string $raw): array
    {
        try {
            $data = Crypt::decrypt($raw);
        } catch (\Throwable) {
            throw new BadRequestHttpException('El código QR no es válido.');
        }

        $this->validateQrPayload($data);

        return $data;
    }

    private function validateQrPayload(array $data)
    {

        $seccionId = $data['seccion_id'] ?? null;
        $horarioId = $data['horario_id'] ?? null;
        $fechaQr   = $data['fecha']      ?? null;

        if (! $seccionId || ! $horarioId || ! $fechaQr) {
            throw new BadRequestHttpException('El código QR no contiene la información necesaria.');
        }

        $hoy = now()->toDateString();

        if ($fechaQr !== $hoy)
            throw new BadRequestHttpException('El código QR ha expirado. Solicitá uno nuevo al docente.');
    }
}
